### ISSUE TITLE
Hangs after boss kill

### ISSUE THREAD

**Issue by Krealle** [Kowson/Details-Damage-Meter-for-3.3.5a#3]
When you kill a raid boss it hangs and doesn't register new combat encounter (trash or boss). Until you reload.

**Comment by Krealle** [comment]
Seems to have something to do with garbage collection, appears to become forced to focus on garbage collection and doesn't register new combat.

**Comment by andrew6180** [comment]
an update to this, I had this issue last night on 25 heigan, which is also a boss I had setup multiple phases for. 

I'm thinking the issue may be details getting 'stuck' trying to track a phase but I'm not entirely sure what phases even do yet.

**Comment by Krealle** [comment]
I'm fairly certain that phases is purely for a encounter details feature. But that specific feature hasn't been implemented yet.

**Comment by Krealle** [comment]
I believe all issues retaining to this bug stems from trying to freeze the parser after boss encounters. Which in my version of the code I've disabled the freezing and have yet to have this bug occur again.

I have yet to happen upon a situation where this has caused any issues. I've tested it in Naxx25/Ulduar25/Voa25/OS25.

**Comment by andrew6180** [comment]
managed to get this bug today. Also found the slash commands `/details disable` and `/details enable` which essentially enables / disables parsing in the same way the current fix attempts do.

It persisted through reloads of the ui, so I went through dropping random debug prints all the way up to `function _details:OnParserEvent(...)` which is linked to `_details.parser_frame:SetScript("OnEvent", _details.OnParserEvent)` 

For some reason, `OnParserEvent` was never being called, and I'm unsure why since I got dc'd and logging back in fixed it.

The only idea I have is for some reason _details.Start() is never being called (which would break the entire addon), `COMBAT_LOG_EVENT_UNFILTERED` is being unregistered / never registered, or some other unknown. 

Going to try with this fix https://github.com/ajseward/Details-Damage-Meter-for-3.3.5a/commit/6486203753d9ebbe46c364ff334804baa7d8efd1 and see if I can encounter the bug again. Still a bandaid fix but I cannot find anywhere that unregisters events for parser_frame.

I also added a debug msg for OnParserEvent here https://github.com/ajseward/Details-Damage-Meter-for-3.3.5a/commit/0a89cbaca8a4d1dee9428cc85105c0d0bc43b579 so if you encounter the bug again, try `/details debug`. It should flood your chat with every event, looking like this 
![image](https://user-images.githubusercontent.com/16847730/82134417-9ba9ff80-97ac-11ea-989f-1216dbedd411.png)

if you get different / no output let me know.

**Comment by Krealle** [comment]
It sounds like you encountered the combat log bug where nothing is registered on the combat log until you relog or reset combat log cache. 

I have found a seemingly permanent fix for the freezing by the way. In the parser under the event of PLAYER_REGEN_DISABLE is where I make sure to unfreeze the parser. So far it has been a perfect solution.

**Comment by andrew6180** [comment]
I'll try pushing that fix then, odd I'd have the combat log bug, I'm running cl_fix which just clears the combat log cache over and over, and I think DBM has a built in cl fix on pull.

**Comment by Kowson** [comment]
Seems to be fixed, will reopen if needed further fix.
